import { Injectable } from '@nestjs/common';
import { 
  Execution as PrismaExecution, 
  ExecutionMetadata as PrismaExecutionMetadata, 
  ExecutionTimeline as PrismaExecutionTimeline 
} from '@prisma/client';
import { AggregateMapper } from '../../../../../infrastructure/database/mappers/AggregateMapper';
import { PersistenceMapper } from '../../../../../infrastructure/database/mappers/PersistenceMapper';
import { Execution, ExecutionProps } from '../../../domain/aggregates/Execution';
import { ExecutionId } from '../../../domain/value-objects/ExecutionId';
import { WorkspaceRef } from '../../../domain/value-objects/WorkspaceRef';
import { IdempotencyKey } from '../../../domain/value-objects/IdempotencyKey';
import { ExecutionContext } from '../../../domain/value-objects/ExecutionContext';
import { RetryPolicy } from '../../../domain/value-objects/RetryPolicy';
import { ExecutionTimeline } from '../../../domain/value-objects/ExecutionTimeline';
import { TimelineEntry } from '../../../domain/value-objects/TimelineEntry';
import { FailureClassification } from '../../../domain/value-objects/FailureClassification';
import { CapabilityRequirement } from '../../../domain/value-objects/CapabilityRequirement';
import { ExecutionStatus } from '../../../domain/enums/ExecutionStatus';
import { ExecutionPriority } from '../../../domain/enums/ExecutionPriority';
import { CapabilityType } from '../../../domain/enums/CapabilityType';

export type PrismaExecutionFull = PrismaExecution & {
  metadata?: PrismaExecutionMetadata | null;
  timeline?: PrismaExecutionTimeline[];
};

@Injectable()
export class ExecutionMapper
  implements
    AggregateMapper<Execution, ExecutionId, PrismaExecutionFull>,
    PersistenceMapper<Execution, ExecutionId, PrismaExecutionFull>
{
  toDomain(model: PrismaExecutionFull): Execution {
    if (!model.metadata) {
      throw new Error(`Execution ${model.id} is missing metadata include`);
    }

    const context = ExecutionContext.create({
      workspaceRef: model.workspaceRef,
      actor: model.metadata.actor,
      intent: model.metadata.intent,
      priority: model.metadata.priority as ExecutionPriority,
    });

    const retryPolicyRaw = model.retryPolicy as any;
    const retryPolicy = RetryPolicy.create({
      maxAttempts: retryPolicyRaw.maxAttempts,
      baseBackoffMs: retryPolicyRaw.baseBackoffMs,
      maxBackoffMs: retryPolicyRaw.maxBackoffMs,
      jitterMs: retryPolicyRaw.jitterMs,
      retryWindowMs: retryPolicyRaw.retryWindowMs,
    });

    let timeline = ExecutionTimeline.EMPTY;
    if (model.timeline) {
      const entries = model.timeline.map((t) =>
        TimelineEntry.create({
          status: t.status as ExecutionStatus,
          occurredAt: t.occurredAt,
          message: t.message,
          actor: t.actor ?? undefined,
        })
      );
      for (const entry of entries) {
        timeline = timeline.append(entry);
      }
    }

    const capabilitiesRaw = model.metadata.capabilities as any[];
    const capabilities = capabilitiesRaw?.map((c) =>
      CapabilityRequirement.create(
        c.type as CapabilityType,
        c.attributes
      )
    ) || [];

    let failure: FailureClassification | undefined;
    if (model.failure) {
      const f = model.failure as any;
      failure = FailureClassification.create({
        type: f.type,
        reason: f.reason,
        isRecoverable: f.isRecoverable,
      });
    }

    const props: ExecutionProps = {
      context,
      workspaceRef: WorkspaceRef.create(model.workspaceRef),
      idempotencyKey: IdempotencyKey.create(model.idempotencyKey),
      status: model.status as ExecutionStatus,
      retryPolicy,
      timeline,
      attemptsMade: model.attemptsMade,
      totalSteps: model.totalSteps,
      completedSteps: model.completedSteps,
      assignedWorkerId: model.assignedWorkerId ?? undefined,
      failure,
      capabilities,
    };

    const execution = Execution.initialize(props, ExecutionId.create(model.id));
    (execution as any)['_version'] = model.version;
    execution.clearDomainEvents();
    return execution;
  }

  toPersistence(aggregate: Execution): PrismaExecutionFull {
    const version = (aggregate as any)['_version'] || 1;

    const metadata: PrismaExecutionMetadata = {
      id: '', // Generated by DB or ignored on update
      executionId: aggregate.id.value,
      actor: aggregate.context.actor,
      intent: aggregate.context.intent,
      priority: aggregate.context.priority,
      capabilities: aggregate.capabilities.map((c) => ({
        type: c.type,
        attributes: c.constraints,
      })) as any,
    };

    const timeline: PrismaExecutionTimeline[] = aggregate.timeline.entries.map((t) => ({
      id: '', // Generated by DB
      executionId: aggregate.id.value,
      status: t.status,
      occurredAt: t.occurredAt,
      message: t.message,
      actor: t.actor ?? null,
    }));

    return {
      id: aggregate.id.value,
      workspaceRef: aggregate.workspaceRef.value,
      idempotencyKey: aggregate.idempotencyKey.value,
      status: aggregate.status,
      retryPolicy: {
        maxAttempts: aggregate.retryPolicy.maxAttempts,
        baseBackoffMs: aggregate.retryPolicy.baseBackoffMs,
        maxBackoffMs: aggregate.retryPolicy.maxBackoffMs,
        jitterMs: aggregate.retryPolicy.jitterMs,
        retryWindowMs: aggregate.retryPolicy.retryWindowMs,
      } as any,
      attemptsMade: aggregate.attemptsMade,
      totalSteps: aggregate.totalSteps,
      completedSteps: aggregate.completedSteps,
      assignedWorkerId: aggregate.assignedWorkerId ?? null,
      failure: aggregate.failure ? {
        type: aggregate.failure.type,
        reason: aggregate.failure.reason,
        isRecoverable: aggregate.failure.isRecoverable,
      } as any : null,
      version: version,
      isDeleted: false,
      deletedAt: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      metadata,
      timeline,
    };
  }
}
