apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: rrss-auto-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: rrss-auto-api
  template:
    metadata:
      labels:
        app: rrss-auto-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              value: "redis://:{{ .Values.redis.password }}@{{ .Release.Name }}-redis:6379"
            - name: DATABASE_URL
              value: "postgresql://postgres:{{ .Values.postgres.password }}@{{ .Release.Name }}-postgres:5432/rrss"
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
