import { ValueObject } from '@rrss-auto/domain';
import { InvalidInvitationTokenException } from '../exceptions/InvalidInvitationTokenException';

export interface InvitationTokenProps {
  value: string;
}

/**
 * Opaque token used to authenticate an invitation acceptance.
 * Generated by the application layer; validated by the domain.
 */
export class InvitationToken extends ValueObject<InvitationTokenProps> {
  private static readonly MIN_LENGTH = 16;

  private constructor(props: InvitationTokenProps) {
    super(props);
  }

  get value(): string {
    return this.props.value;
  }

  public static create(value: string): InvitationToken {
    if (!value || value.trim().length === 0) {
      throw new InvalidInvitationTokenException('Invitation token cannot be empty');
    }

    const trimmed = value.trim();

    if (trimmed.length < InvitationToken.MIN_LENGTH) {
      throw new InvalidInvitationTokenException(
        `Invitation token must be at least ${InvitationToken.MIN_LENGTH} characters`,
      );
    }

    return new InvitationToken({ value: trimmed });
  }
}
