export enum CredentialProvider {
  SYSTEM = 'SYSTEM',
  AWS_SECRETS_MANAGER = 'AWS_SECRETS_MANAGER',
  HASHICORP_VAULT = 'HASHICORP_VAULT',
  GCP_SECRET_MANAGER = 'GCP_SECRET_MANAGER',
  AZURE_KEY_VAULT = 'AZURE_KEY_VAULT',
}
